#!/bin/bash
#
# Build Docs and Package before commiting code

npm run build
npm run build:types
npm run docs
touch docs/.nojekyll
git add .

echo "Built production package and appended new docs Automagically!"